### ISSUE TITLE
Which of the thermal parameters corresponds to ECS / TCR?

### ISSUE THREAD

**Issue by tammyt123** [FrankErrickson/MimiFAIRv2.jl#12]
In the thermal parameters file read from Zenodo, it's not super clear to me which (if any) of these are ECS / TCR. I also don't see where in the monte carlo script ECS / TCR is being resampled -- could you please help clarify this for me? Thanks!

**Comment by FrankErrickson** [comment]
Hi @tammyt123,

In FAIR, the ECS and TCR are used to calculate parameters in the model that govern the different thermal response timescales. ECS and TCR aren't specifically set in the model with a `set_param!()` call. The function that does this calculation is in the `src/helper_functions.jl` file here: 

https://github.com/FrankErrickson/MimiFAIRv2.jl/blob/61373fb28b1c75a13f24812c814f5a6582d428b4/src/helper_functions.jl#L9

The parameters that are actually set are called `d1`, `d2`, `d3` and `q1`, `q2` and `q3`, and so that's why you see those parameter column names in the thermal parameter file. 

If you did want to get the TCR and ECS values that these sampled d and q terms corresponded to, you could rearrange the equations in that helper function so that it gave TCR and ECS as outputs when you input the d and q values.

**Comment by tammyt123** [comment]
Thanks so much, Frank! When I try to solve for TCR and ECS I still need a value for F2x -- is this specified somewhere else? Or am I miscalculating something?
